---
title: "FY21_Inq_App_Flow_Funnel_Rinck"
author: "Office of Marketing and Brand Management"
date: "11/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(knitr)
library(ggplot2)
library(forcats)
library(patchwork)
suppressPackageStartupMessages(library("dplyr"))
```

## Year Over Year Conversions

```{r cars, fig.height=4, fig.width=8}
DAAData <- read.csv("C:/Users/christine.iyer/Box/FY21 Weekly Admissions Reports Summary to Inform Agency Campaigns/Reports/DAA_12-01-2020.csv", header = T, stringsAsFactors = F)
colors <- c("#60c7d1", "#731012", "#0e1033", "#f5a800")
```

```{r}
# Read data
#MacOnly 

#DAA <- read.csv("C:/Users/christine.iyer/Box/FY21 Weekly Admissions Reports Summary to Inform Agency Campaigns/Reports/DAA_11-18-2020.csv", header = T, stringsAsFactors = F)
Date <- Sys.Date()-1
#WINDOWS

#DAA <- read.csv("C:/Users/christine.iyer/Box/FY21 Weekly Admissions Reports Summary to Inform Agency Campaigns/Reports/DAA_11-13-2020.csv", header = T, stringsAsFactors = F)
```

```{r}
# Convert dates
DAA1 <- DAAData %>% 
  mutate_at(
    vars("Birthdate", "App.Application.Date", "Initial.Source.Date", "Created.Date"), 
    as.Date,
    format = "%m/%d/%Y")

DAA1$Month_I_N <- as.numeric(format(as.Date(DAA1$Initial.Source.Date),"%m")) # Month's number

DAA1$Month_I_M  <- months(as.Date(DAA1$Initial.Source.Date), abbreviate=TRUE) 

DAA1$Month_A_N <- as.numeric(format(as.Date(DAA1$App.Application.Date),"%m")) # Month's number

DAA1$Month_A_M  <- months(as.Date(DAA1$App.Application.Date), abbreviate=TRUE) 

DAA1$Yr_I_Y <- as.numeric(format(as.Date(DAA1$Initial.Source.Date),"%Y")) # Month's number

DAA1$Yr_A_Y <- as.numeric(format(as.Date(DAA1$App.Application.Date),"%Y")) # Month's number



```




```{r}
### Factor Values in Raw Data


### __Fiscal Year Initial Source Date__
#create FY variable on initial source date
DAA1 <- DAA1 %>% mutate(
  FiscalYear = ifelse(Initial.Source.Date>="2015-07-01" & Initial.Source.Date <= "2016-06-30", "FY16", 
                      ifelse(Initial.Source.Date>="2016-07-01" & Initial.Source.Date <= "2017-06-30", "FY17",
                             ifelse(Initial.Source.Date>="2017-07-01" & Initial.Source.Date <= "2018-06-30", "FY18",
                                    ifelse(Initial.Source.Date>="2018-07-01" & Initial.Source.Date <= "2019-06-30", "FY19",
                                           ifelse(Initial.Source.Date>="2019-07-01" & Initial.Source.Date <= "2020-06-30", "FY20",
                                                  ifelse(Initial.Source.Date>="2020-07-01" & Initial.Source.Date <= "2021-06-30", "FY21","FY15 or earlier")))))))

```






```{r}
### __Student Type__
#if student type is and the student is a lead, we can assume this a a first-year student because we only buy leads who are first-year bound. If student type is blank and the career is graduate, the student type will also be graduate.
DAA1 <- DAA1 %>% 
  mutate(Student.Type = ifelse(Student.Stage == "Lead", "First-Year Student",
                               ifelse(Career == "Graduate", "Graduate", Student.Type)))
```




```{r}
### __Student Stage__
#remove leads and classify other student stages
DAA1 <- DAA1 %>% mutate(Student.Stage = ifelse(grepl("Applic", Student.Stage), "Applicant", Student.Stage))
DAA1 <- DAA1 %>% filter(Student.Stage != "Lead")
```




```{r}
### __Anticipated Start__
#tidy up the Start term year choices
DAA1 <- DAA1 %>% 
  mutate(Anticipated.Start.Term.Year= 
                        ifelse(Anticipated.Start.Term.Year == "Sep-18", "Fall 2018",
                               ifelse(Anticipated.Start.Term.Year == "Sep-19", "Fall 2019", 
                                      ifelse(Anticipated.Start.Term.Year == "Jan-19", "Spring 2019", 
                                             ifelse(Anticipated.Start.Term.Year == "Summer 2021 2021", "Fall 2021", 
                                                    ifelse(Anticipated.Start.Term.Year == "Jan-18", "Spring 2018", 
                                                           ifelse(Anticipated.Start.Term.Year == "2018", "Fall 2018", 
                                                                  ifelse(Anticipated.Start.Term.Year == "2020", "Fall 2020", 
                                                                         ifelse(Anticipated.Start.Term.Year == "Spring 2021 2021", "Spring 2021", 
                                                                                ifelse(Anticipated.Start.Term.Year == "Spring 2019 2019", "Spring 2019", 
                                                                                       ifelse(Anticipated.Start.Term.Year == "Summer 2022 2022", "Fall 2022", 
                                                                                              ifelse(Anticipated.Start.Term.Year == "Spring 2022 2022", "Spring 2022", 
                                                                                                     ifelse(Anticipated.Start.Term.Year == "Summer 2023", "Fall 2023", ifelse(Anticipated.Start.Term.Year == "Summer 2019 2019", "Fall 2019", 
ifelse(Anticipated.Start.Term.Year == "Fall 2020 2020", "Fall 2020", 
ifelse(Anticipated.Start.Term.Year == "Fall 2021 2021", "Fall 2021",
    ifelse(Anticipated.Start.Term.Year == "Summer 2020", "Fall 2020", 
           ifelse(Anticipated.Start.Term.Year == "Summer 2019", "Fall 2019", 
                  ifelse(Anticipated.Start.Term.Year == "Summer 2021", "Fall 2021", 
                         ifelse(Anticipated.Start.Term.Year == "Summer 2018", "Fall 2018", 
                                ifelse(Anticipated.Start.Term.Year == "Summer 2022", "Fall 2022", 
                                       ifelse(Anticipated.Start.Term.Year == "Fall 2022 2022", "Fall 2022", Anticipated.Start.Term.Year))))))))))))))))))))))
```



```{r}
### __Application Status__

#group by app status
AppliedCats <- c("Withdrawn (Before Decision)", "Incomplete", "Hold (More Information Needed)", "Denied", "Complete (No Decision)", "Complete (Waitlisted)") 
DAA1 <- DAA1 %>% 
  mutate(App.Application.Status = 
           ifelse(App.Application.Status %in% AppliedCats, "Applied",
                  ifelse(grepl("Confirm", App.Application.Status), "Confirmed",
                          ifelse(grepl("Enrolled", App.Application.Status), "Enrolled", 
                                 ifelse(grepl("Admit", App.Application.Status), "Admitted", App.Application.Status)))))


```




```{r}
### __Student Age Group at Time of Inq/App__
#since we are targeting by age group, we want to see ages at the time of inquiry
DAA2 <- DAA1 %>% mutate(AgeAtInquiry = round(difftime(Initial.Source.Date, Birthdate, units = "weeks"),0), 
                        Age_Y = as.integer(round(AgeAtInquiry/52, 0)), 
                        
                        AgeGroup = 
                          ifelse(Age > 13 & Age_Y <=19, "19 and Under", 
                                 ifelse(Age_Y > 19 & Age_Y < 25, "20-25", 
                                        ifelse(Age_Y >= 25, "26 and Up", "Unknown"))), 
                        AgeGroup = ifelse(is.na(AgeAtInquiry) , "Unknown", AgeGroup), 
                        AgeGroupforTransfers = ifelse(AgeGroup == "Unknown", "Unknown Age",
                                                      ifelse(Age_Y >= 0 & Age_Y < 19, "Too Young", 
                                                        ifelse(Age_Y > 24, "Too Old", 
                                                          ifelse(Age_Y >=19 & Age_Y <= 24, "Transfer Age","Unknown"))))) 
```



```{r}

### __Region__
targetedStates <- c("Massachusetts", "Connecticut", "New Hampshire")
OtherNE <- c("Rhode Island", "Vermont")
DAA2 <- DAA2 %>% mutate(Region = ifelse(Primary.State.Province == "Maine", "Maine", 
                                        ifelse(Primary.State.Province %in% targetedStates, "Targeted OOS", 
                                               ifelse(Primary.State.Province %in% OtherNE, "Other NE", "Remaining USA"))))
```


 


```{r}

### __Stealth Apps__
DAA3 <- DAA2 %>% 
  mutate(Stealth = ifelse(Initial.Referral.Source == "APPL", "Stealth", "Not Stealth"))
#unique(DAA$Stealth)
DAA4 <- DAA3 %>% 
  mutate(Student.Stage = ifelse(Student.Stage == "", "Inquiry", Student.Stage), 
         App.Application.Status = ifelse(App.Application.Status == "" & Student.Stage == "Applicant", "Applied", App.Application.Status ), 
         App.Application.Status = ifelse(App.Application.Status == "" & Student.Stage == "Inquiry", "Inquiry", App.Application.Status)) %>% 
  group_by(Stealth, Career, Student.Type, Anticipated.Start.Term.Year, Student.Stage, App.Application.Status, AgeGroup, Region, FiscalYear, AgeGroupforTransfers, Initial.Source.Date, App.Application.Date, Month_I_N,Month_I_M,  Month_A_N, Month_A_M, Yr_I_Y, Yr_A_Y ) %>% 
  summarise(n = n()) 
```
 

 
```{r}
### __Narrow FY__
SelectFY <- c("Fall 2018", "Fall 2019", "Fall 2020", "Fall 2021")
DAA4 <- DAA4 %>% filter(Anticipated.Start.Term.Year %in% SelectFY)

DAA4$Month_I_M <- factor(DAA4$Month_I_M , levels = c("Jul", "Aug", "Sep", "Oct", "Nov", "Dec",  "Jan", "Feb", "Mar", "Apr", "May", "Jun"))

DAA4$Month_A_M <- factor(DAA4$Month_A_M , levels = c("Jul", "Aug", "Sep", "Oct", "Nov", "Dec",  "Jan", "Feb", "Mar", "Apr", "May", "Jun"))


unique(DAA4$Anticipated.Start.Term.Year)
```
       

```{r}
# Age Groups

AgeTransfers <- c("Unknown Age", "Transfer Age")
filterForWA <- c("26 and Up", "Unknown")
DAA4 <- DAA4 %>% mutate(Aud_P = 
                  ifelse(Stealth == "Not Stealth" & 
                          Region == "Maine" & 
                          Career == "Undergraduate" & 
                          Student.Type == "First-Year Student" & 
                          grepl("^Fall", Anticipated.Start.Term.Year)& 
                          AgeGroup == "19 and Under", "HSUGIS",
                         ifelse(Stealth == "Not Stealth" &
                                  Region == "Targeted OOS" & 
                                  Career == "Undergraduate" & 
                                  Student.Type == "First-Year Student" & 
                                  grepl("^Fall",Anticipated.Start.Term.Year) &
                                  AgeGroup == "19 and Under", "HSUGOS",
                                ifelse(Stealth == "Not Stealth" &
                                         Region == "Maine" & 
                                         Career == "Undergraduate" & 
                                         Student.Type == "Transfer" & 
                                         grepl("^Fall", Anticipated.Start.Term.Year)&
                                         AgeGroupforTransfers %in% AgeTransfers, "CUTRIS",
                                       ifelse(Stealth == "Not Stealth" & 
                                                Region == "Targeted OOS" & 
                                                Career == "Undergraduate" & 
                                                Student.Type == "Transfer" & grepl("^Fall", Anticipated.Start.Term.Year) & 
                                                AgeGroupforTransfers %in% AgeTransfers, "CUTROS",
                                              ifelse(Stealth == "Not Stealth" &
                                                     Career == "Undergraduate" & 
                                                       grepl("^Fall", Anticipated.Start.Term.Year) &
                                                       AgeGroup %in% filterForWA, "WADC",
                                                     ifelse(Stealth == "Not Stealth" & 
                                                              Region == "Maine" & 
                                                              Career == "Graduate" & 
                                                              Student.Type == "Graduate" & 
                                                              grepl("^Fall", Anticipated.Start.Term.Year)& 
                                                            AgeGroup == "20-25", "CUGRIS",
                                                            
                                                            ifelse(Stealth == "Not Stealth" & 
                                                                     Region == "Maine" & 
                                                                     Career == "Graduate" & 
                                                                     Student.Type == "Graduate" & 
                                                                     grepl("^Fall", Anticipated.Start.Term.Year)&
                                                                     AgeGroup == "26 and Up", "WAGRIS",
                                                                   ifelse(Stealth == "Not Stealth" & 
                                                                           Region == "Targeted OOS" & 
                                                                           #Student.Stage == "Inquiry" & 
                                                                           Career == "Graduate" & 
                                                                           Student.Type == "Graduate" & 
                                                                           grepl("^Fall", Anticipated.Start.Term.Year)&
                                                                           AgeGroup == "20-25", "CUGROS",
                                                                          ifelse(Stealth == "Not Stealth" & 
                                                                                 Region == "Targeted OOS" & 
                                                                                 Career == "Graduate" & 
                                                                                 Student.Type == "Graduate" & 
                                                                                 grepl("^Fall", Anticipated.Start.Term.Year)& 
                                                                                 AgeGroup == "26 and Up", "WAGROS", "Other"))))))))), 
                Stage = "Inquiry")
```

```{r}
Apps5 <- DAA4 %>% mutate(Aud_P = 
                  ifelse(Student.Stage == "Applicant" & 
                          Region == "Maine" & 
                          Career == "Undergraduate" & 
                          Student.Type == "First-Year Student" & 
                          grepl("^Fall", Anticipated.Start.Term.Year)& 
                          AgeGroup == "19 and Under", "HSUGIS",
                         ifelse(
                           Student.Stage == "Applicant" &
                                  Region == "Targeted OOS" & 
                                  Career == "Undergraduate" & 
                                  Student.Type == "First-Year Student" & 
                                  grepl("^Fall",Anticipated.Start.Term.Year) &
                                  AgeGroup == "19 and Under", "HSUGOS",
                                ifelse(Student.Stage == "Applicant" &
                                         Region == "Maine" & 
                                         Career == "Undergraduate" & 
                                         Student.Type == "Transfer" & 
                                         grepl("^Fall", Anticipated.Start.Term.Year)&
                                         AgeGroupforTransfers %in% AgeTransfers, "CUTRIS",
                                       ifelse(Student.Stage == "Applicant" & 
                                                Region == "Targeted OOS" & 
                                                Career == "Undergraduate" & 
                                                Student.Type == "Transfer" & grepl("^Fall", Anticipated.Start.Term.Year) & 
                                                AgeGroupforTransfers %in% AgeTransfers, "CUTROS",
                                              ifelse(Student.Stage == "Applicant" &
                                                     Career == "Undergraduate" & 
                                                       grepl("^Fall", Anticipated.Start.Term.Year) &
                                                       AgeGroup %in% filterForWA, "WADC",
                                                     ifelse(Student.Stage == "Applicant" &
                                                              Region == "Maine" & 
                                                              Career == "Graduate" & 
                                                              Student.Type == "Graduate" & 
                                                              grepl("^Fall", Anticipated.Start.Term.Year)& 
                                                            AgeGroup == "20-25", "CUGRIS",
                                                            
                                                            ifelse(Student.Stage == "Applicant" & 
                                                                     Region == "Maine" & 
                                                                     Career == "Graduate" & 
                                                                     Student.Type == "Graduate" & 
                                                                     grepl("^Fall", Anticipated.Start.Term.Year)&
                                                                     AgeGroup == "26 and Up", "WAGRIS",
                                                                   ifelse(Student.Stage == "Applicant" &
                                                                          Region == "Targeted OOS" & 
                                                                           Career == "Graduate" & 
                                                                           Student.Type == "Graduate" & 
                                                                           grepl("^Fall", Anticipated.Start.Term.Year)&
                                                                           AgeGroup == "20-25", "CUGROS",
                                                                          ifelse(Student.Stage == "Applicant" &
                                                                                 Region == "Targeted OOS" & 
                                                                                 Career == "Graduate" & 
                                                                                 Student.Type == "Graduate" & 
                                                                                 grepl("^Fall", Anticipated.Start.Term.Year)& 
                                                                                 AgeGroup == "26 and Up", "WAGROS", "Other"))))))))), 
                Stage = "Applicant")

```


```{r}
DAA4 <- DAA4 %>% mutate(Stage1 = Stage)
InqsApps <- merge(DAA4, Apps5, all = T)

AnotherIA <- left_join(DAA4, Apps5
                       )

# dim(AnotherIA)
# kable(head(AnotherIA, 25))
InqsApps <- InqsApps %>% filter(Aud_P != "Other")
#write.csv(InqsApps, "C:/Users/christine.iyer/Box/FY21 Weekly Admissions Reports Summary to Inform Agency Campaigns/TidiedInqAppReports/FotTableauYoY.csv", row.names = F)
```




### Conversions



```{r HSUGIS,fig.height=4, fig.width=8}
FY <- c("FY18", "FY19", "FY20", "FY21")
Inquiries <- DAA4 %>% filter(Stealth == "Not Stealth")
HSUGIS_I <- Inquiries %>%
  filter(Region == "Maine" & 
       Career == "Undergraduate" &  
       Student.Type == "First-Year Student" &
       AgeGroup == "19 and Under", 
       FiscalYear %in% FY) %>% 
  rename(Inquiries = n) %>% 
  select(-Month_A_N, -Month_A_M ) %>% 
  group_by(Month_I_M, Anticipated.Start.Term.Year) %>% 
  summarise(Inquiries = sum(Inquiries)) 


g <- ggplot(data = HSUGIS_I, aes(x = Month_I_M, y = Inquiries - lag(Inquiries), group = Anticipated.Start.Term.Year, colour=Anticipated.Start.Term.Year)) + 
     geom_line(size = 1.2) +
     geom_point() +
     theme_bw()+
  scale_color_manual(values = colors) + 
  theme(legend.position = "none") + 
  theme(axis.text.x = element_text(angle = 45)) + 
  ylab("Inquiries")+ 
  xlab("")

  

HSUGIS_A <- DAA4 %>% 
  filter(Region == "Maine" & 
       Career == "Undergraduate" &  
       Student.Type == "First-Year Student" &
       AgeGroup == "19 and Under", 
       FiscalYear %in% FY) %>% 
  rename(Applications = n) %>% 
  select(-Month_I_N, -Month_I_M ) %>% 
  group_by(Month_A_N, Month_A_M, Anticipated.Start.Term.Year) %>% 
  summarise(Applications = sum(Applications)) %>% na.omit()



h <- ggplot(data = HSUGIS_A, aes(x = Month_A_M, y = Applications - lag(Applications), group = Anticipated.Start.Term.Year, colour=Anticipated.Start.Term.Year)) + 
     geom_line(size = 1.2) +
     geom_point() +
     theme_bw()+
  scale_color_manual(values = colors)+ 
  theme(axis.text.x = element_text(angle = 45))+
    theme(legend.position="bottom")+ 
  ylab("Applicants") + 
  xlab("")
```

**In-State HS Inquiries** 

```{r fig.height=4, fig.width=8}
g
```

**In-State HS Applicants** 

```{r fig.height=4, fig.width=8}
h
```



```{r HSUGOS, fig.height=4, fig.width=8}
FY <- c("FY18", "FY19", "FY20", "FY21")
Inquiries <- DAA4 %>% filter(Stealth == "Not Stealth")
HSUGIS_O <- Inquiries %>%
  filter(Region == "Targeted OOS" & 
       Career == "Undergraduate" &  
       Student.Type == "First-Year Student" &
       AgeGroup == "19 and Under", 
       FiscalYear %in% FY) %>% 
  rename(Inquiries = n) %>% 
  select(-Month_A_N, -Month_A_M ) %>% 
  group_by(Month_I_M, Anticipated.Start.Term.Year) %>% 
  summarise(Inquiries = sum(Inquiries)) 


g <- ggplot(data = HSUGIS_O, aes(x = Month_I_M, y = Inquiries - lag(Inquiries), group = Anticipated.Start.Term.Year, colour=Anticipated.Start.Term.Year)) + 
     geom_line(size = 1.2) +
     geom_point() +
     theme_bw()+
  scale_color_manual(values = colors) + 
  theme(legend.position = "none") + 
  theme(axis.text.x = element_text(angle = 45)) + 
  ylab("Inquiries")+ 
  xlab("")

  

HSUGOS_A <- DAA4 %>% 
  filter(Region == "Targeted OOS" & 
       Career == "Undergraduate" &  
       Student.Type == "First-Year Student" &
       AgeGroup == "19 and Under", 
       FiscalYear %in% FY) %>% 
  rename(Applications = n) %>% 
  select(-Month_I_N, -Month_I_M ) %>% 
  group_by(Month_A_N, Month_A_M, Anticipated.Start.Term.Year) %>% 
  summarise(Applications = sum(Applications)) %>% na.omit()



h <- ggplot(data = HSUGOS_A, aes(x = Month_A_M, y = Applications - lag(Applications), group = Anticipated.Start.Term.Year, colour=Anticipated.Start.Term.Year)) + 
     geom_line(size = 1.2) +
     geom_point() +
     theme_bw()+
  scale_color_manual(values = colors)+ 
  theme(axis.text.x = element_text(angle = 45))+
    theme(legend.position="bottom")+ 
  ylab("Applicants") + 
  xlab("")
```

**Out-of-State HS Inquiries** 

```{r fig.height=4, fig.width=8}
g
```

**Out-of-State HS Applicants** 

```{r fig.height=4, fig.width=8}
h
```












```{r CUTRIS, fig.height=4, fig.width=8}
FY <- c("FY18", "FY19", "FY20", "FY21")
Inquiries <- DAA4 %>% filter(Stealth == "Not Stealth")
CUTRIS_I <- Inquiries %>%
  filter(Region == "Maine" & 
       Career == "Undergraduate" &  
       Student.Type == "Transfer" &
       FiscalYear %in% FY) %>% 
  rename(Inquiries = n) %>% 
  select(-Month_A_N, -Month_A_M ) %>% 
  group_by(Month_I_M, Anticipated.Start.Term.Year) %>% 
  summarise(Inquiries = sum(Inquiries)) 


g <- ggplot(data = CUTRIS_I, aes(x = Month_I_M, y = Inquiries - lag(Inquiries), group = Anticipated.Start.Term.Year, colour=Anticipated.Start.Term.Year)) + 
     geom_line(size = 1.2) +
     geom_point() +
     theme_bw()+
  scale_color_manual(values = colors) + 
  theme(legend.position = "none") + 
  theme(axis.text.x = element_text(angle = 45)) + 
  ylab("Inquiries")+ 
  xlab("")

  

CUTRIS_A <- DAA4 %>% 
  filter(Region == "Maine" & 
       Career == "Undergraduate" &  
       Student.Type == "Transfer" &
       FiscalYear %in% FY) %>% 
  rename(Applications = n) %>% 
  select(-Month_I_N, -Month_I_M ) %>% 
  group_by(Month_A_N, Month_A_M, Anticipated.Start.Term.Year) %>% 
  summarise(Applications = sum(Applications)) %>% na.omit()



h <- ggplot(data = CUTRIS_A, aes(x = Month_A_M, y = Applications - lag(Applications), group = Anticipated.Start.Term.Year, colour=Anticipated.Start.Term.Year)) + 
     geom_line(size = 1.2) +
     geom_point() +
     theme_bw()+
  scale_color_manual(values = colors)+ 
  theme(axis.text.x = element_text(angle = 45))+
    theme(legend.position="bottom")+ 
  ylab("Applicants") + 
  xlab("")
```

**In-State TR Inquiries**

```{r fig.height=4, fig.width=8}
g
```

**In-State TR Applicants**

```{r fig.height=4, fig.width=8}
h
```




```{r  CUTROS, fig.height=4, fig.width=8}
FY <- c("FY18", "FY19", "FY20", "FY21")
Inquiries <- DAA4 %>% filter(Stealth == "Not Stealth")
CUTROS_O <- Inquiries %>%
  filter(Region == "Targeted OOS" & 
       Career == "Undergraduate" &  
       Student.Type == "Transfer" &
       FiscalYear %in% FY) %>% 
  rename(Inquiries = n) %>% 
  select(-Month_A_N, -Month_A_M ) %>% 
  group_by(Month_I_M, Anticipated.Start.Term.Year) %>% 
  summarise(Inquiries = sum(Inquiries)) 


g <- ggplot(data = CUTROS_O, aes(x = Month_I_M, y = Inquiries - lag(Inquiries), group = Anticipated.Start.Term.Year, colour=Anticipated.Start.Term.Year)) + 
     geom_line(size = 1.2) +
     geom_point() +
     theme_bw()+
  scale_color_manual(values = colors) + 
  theme(legend.position = "none") + 
  theme(axis.text.x = element_text(angle = 45)) + 
  ylab("Inquiries")+ 
  xlab("")

  

CUTROS_A <- DAA4 %>% 
  filter(Region == "Targeted OOS" & 
       Career == "Undergraduate" &  
       Student.Type == "Transfer" & 
       FiscalYear %in% FY) %>% 
  rename(Applications = n) %>% 
  select(-Month_I_N, -Month_I_M ) %>% 
  group_by(Month_A_N, Month_A_M, Anticipated.Start.Term.Year) %>% 
  summarise(Applications = sum(Applications)) %>% na.omit()



h <- ggplot(data = CUTROS_A, aes(x = Month_A_M, y = Applications - lag(Applications), group = Anticipated.Start.Term.Year, colour=Anticipated.Start.Term.Year)) + 
     geom_line(size = 1.2) +
     geom_point() +
     theme_bw()+
  scale_color_manual(values = colors)+ 
  theme(axis.text.x = element_text(angle = 45))+
    theme(legend.position="bottom")+ 
  ylab("Applicants") + 
  xlab("")
```


**Out-of-State TR Inquiries**

```{r fig.height=4, fig.width=8}
g
```


**Out-of-State TR Applicants**

```{r fig.height=4, fig.width=8}
h
```

```{r}
write.csv(DAA4, "C:/Users/christine.iyer/Box/FY21 Weekly Admissions Reports Summary to Inform Agency Campaigns/TidiedInqAppReports/FotTableauYoY.csv", row.names = F)
```

